config/routes.rb
Mozapolis::Application.routes.draw do

  root :to => "static#home"

  match 'admin' => "secret#home"
  match 'register' => "static#register"
  resources :pages

  devise_for :fans, :controllers => { :registrations => :fan_registrations }
  resources :fans, :only => [:show, :index]
  resources :fans do 
    resources :comments
  end

  as :fan do
    get    'fan/signin'  => 'devise/sessions#new',     :as => :new_fan_session
    post   'fan/signin'  => 'devise/sessions#create',  :as => :fan_session
    delete 'fan/signout' => 'devise/sessions#destroy', :as => :destroy_fan_session
  end

  devise_for :artists, :controllers => { :registrations => :artist_registrations }
  resources :artists, :only => [:show, :index]
  resources :artists do 
    resources :comments
  end
  as :artist do
    get    'artist/signin'  => 'devise/sessions#new',     :as => :new_artist_session
    post   'artist/signin'  => 'devise/sessions#create',  :as => :artist_session
    delete 'artist/signout' => 'devise/sessions#destroy', :as => :destroy_artist_session
  end

  devise_for :users

  
  resources :notifications
  resources :playlists do
    collection { post :sort }
    resources :ptracks do 
      collection { post :addsong }
    end
  end
  resources :genres
  resources :pictures, :only => [:index, :create, :destroy]
  resources :videos do
    collection { post :sort }
    resources :comments
  end

  resources :events do
    collection { post :sort }
    resources :comments
  end
  resources :articles do
    collection { post :sort }
    resources :comments
  end

  resources :galleries do
    collection { post :sort }
    resources :comments
    resources :images
  end
  resources :images do 
    collection { post :sort }
    resources :comments
  end
  resources :albums do
    collection { post :sort }
    collection { post :upvote }
    collection { post :downvote }
    collection { post :unvote }
    resources :comments
    resources :songs
  end

  
  resources :songs do
    resources :comments
    collection { post :sort }
    collection { post :upvote }
    collection { post :downvote }
    collection { post :unvote }
  end

  namespace :admin do
    resources :articles
    resources :events
    resources :galleries
  end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	belongs_to :artist
	has_many :images
	has_many :comments, as: :commentable  
	
	# Friendly URLS
	# -----
	extend FriendlyId
	friendly_id :title, use: :slugged

	attr_accessible :description, :title, :cover
	
	validates :title,
	          presence: true,
	          length: {
	            minimum: 2, maximum: 40,
	            :message => "2-40 characters."
	          }
	
	validates :description,
	          allow_blank: true,
	          length: {
	            minimum: 2, maximum: 500,
	            :message => "2-500 characters."
	          }
	validates :cover, :attachment_presence => true
	has_attached_file :cover, 
                      :styles => {
                        :small => "150x150#", 
                        :full_small => "150x150>", 
                        :medium => "400x400#", 
                        :full_medium => "400x400>", 
                        :large => "900x900#", 
                        :full_large => "900x900>",
                        :avatar => "60x60#"
                      },
	                  :url => "/system/galleries/cover/:id/:style/:basename.:extension",
	                  :path => ":rails_root/public/system/galleries/cover/:id/:style/:basename.:extension"
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < ApplicationController

  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  def show
    @gallery = Gallery.find(params[:id])
    @artist = @gallery.artist
    @images = @gallery.images

    # Comments
    @commentable = @gallery
    @comments = @commentable.comments
    @comment = Comment.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  def new
    @artist = current_artist
    @gallery = @artist.galleries.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  def create
    @artist = current_artist
    @gallery = @artist.galleries.build(params[:gallery])
    if @gallery.save
      flash[:notice] = "You have created a gallery succesfully. Wasn't that easy?"
      redirect_to admin_galleries_url
    else
      render :action => 'new'
    end
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def sort
    params[:gallery].each_with_index do |id, index|
      Gallery.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end
  def index
    @galleries = current_artist.galleries.order(:position)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  def show
    @gallery = Gallery.find(params[:id])
    @artist = @gallery.artist
    @images = @gallery.images

    # Comments
    @commentable = @gallery
    @comments = @commentable.comments
    @comment = Comment.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  def new
    @artist = current_artist
    @gallery = @artist.galleries.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  def create
    @artist = current_artist
    @gallery = @artist.galleries.build(params[:gallery])
    if @gallery.save
      flash[:notice] = "You have created a gallery succesfully. Wasn't that easy?"
      redirect_to galleries_url
    else
      render :action => 'new'
    end
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { 
        flash[:error] = "Gallery destroyed."
        redirect_to galleries_url 
      }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/galleries_helper.rb
module Admin::GalleriesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/admin/galleries/_form.html.erb
<%= simple_form_for [:admin,@gallery], :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :title %>
  <%= f.input :description, :input_html => { :class => "span4", :rows => 5 } %>
  <hr>
  <%= f.input :cover %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                albums_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/galleries/edit.html.erb
<%= provide(:title, 'Editing Gallery: '+ @gallery.title) %>
<div class="row">
	<div class="span6 offset3">

		<ul class="breadcrumb">
		  <li>
		    <%= link_to_icon "lock", "Top Secret", admin_path %> <span class="divider">/</span>
		  </li>
		  <li>
		    <%= link_to_icon "picture", "Manage Galleries", admin_galleries_path %> <span class="divider">/</span>
		  </li>
		  <li class="active"><i class="icon-edit"></i> Editing Gallery: <strong><%= link_to @gallery.title, @gallery %></strong></li>
		</ul>	

		<div class="well">
			<%= render :partial => 'form' %>
		</div>
	</div>

	<div class="span3">
		<h6>Current Image</h6>
		<% if @gallery.cover.file? %>
			<p><%= image_tag @gallery.cover.url(:small) %></p>
		<% else %>
			<p>Please upload an gallery cover.</p>
		<% end %>
	</div>
</div>

app/views/admin/galleries/index.html.erb
<%= provide(:title, 'Manage Galleries') %>
<div class="row">
  	<div class="span12">
    	<ul class="breadcrumb">

		  <li>
		    <%= link_to_icon "lock", "Top Secret", admin_path %> <span class="divider">/</span>
		  </li>
    	  <li class="active"><i class="icon-picture"></i> Manage Galleries</li>
    	</ul>
	</div>
</div>
<div class="row">
	<div class="span3">
		<div class="well">
			<h4><i class="icon-wrench"></i> Gallery Admin</h4>
			<hr>
			<p>You can edit, view, or delete any gallery.</p>
		</div>
	</div>
	<div class="span9">
		<div class="pull-right">
			<%= link_to "<i class='icon-plus'></i> New Gallery".html_safe, new_admin_gallery_path, :class => "btn btn-success" %>
		</div>
		<h2>All Galleries</h2>
		<ul class="thumbnails">
			<% @galleries.each do |gallery| %>
			<li class="span3">
				<div class="thumbnail">
					<%= image_tag(gallery.cover.url(:medium)) %>
					<div class="caption">
						<h5><%= link_to gallery.title, gallery %></h5>
						<p>
			            	<%= link_to "<i class='icon-wrench'></i>".html_safe, gallery_images_path(gallery), :class => "btn btn-mini btn-inverse", :rel => "tooltip", :title => "Gallery manager, you can edit and upload images here." %>
			            	<%= link_to "<i class='icon-plus'></i>".html_safe, new_gallery_image_path(gallery), :class => "btn btn-mini btn-success", :rel => "tooltip", :title => "Add a new image to the gallery." %>
			            	<%= link_to "<i class='icon-edit'></i>".html_safe, edit_admin_gallery_path(gallery), :class => 'btn btn-mini btn-info', :rel => "tooltip", :title =>  "Edit gallery details and cover image."  %>
			            	<%= link_to "<i class='icon-remove'></i>".html_safe,
			            	            gallery_path(gallery),
			            	            :method => :delete,
			            	            :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
			            	            :class => 'btn btn-mini btn-danger',
			            	            :rel => "tooltip", :title => "Delete this gallery forever." %>
			            </p>
   			</li>
			<% end %>
		</ul>
		<% if @galleries.empty? %>
			<div class="alert alert-info">
        		There are no galleries. <%= link_to "<i class='icon-plus'></i> Click here to create one.".html_safe, new_admin_gallery_path %>
			</div>
		<% end %>
		<hr>
	    <div class="dropzone">
	      <i class="icon-plus"></i>
	      <p>Drop images here to upload into a new album.</p>
	    </div>
	</div>
</div>

app/views/admin/galleries/new.html.erb
<%= provide(:title, 'New Gallery') %>
<div class="row">
	<div class="span6 offset3">

		<ul class="breadcrumb">
		  <li>
		    <%= link_to_icon "lock", "Top Secret", admin_path %> <span class="divider">/</span>
		  </li>
		  <li>
		    <%= link_to_icon "picture", "Manage Galleries", admin_galleries_path %> <span class="divider">/</span>
		  </li>
		  <li class="active"><i class="icon-plus"></i> New Gallery</li>
		</ul>	

		<div class="well">
			<%= render :partial => 'form' %>
		</div>
	</div>
</div>

app/views/admin/galleries/show.html.erb
<div class="row">
	<div class="span6">
		<h2><%= @gallery.title %> Images</h2>
		<ul class="thumbnails">
			<% @images.each do |img| %>
			<li class="span3">
				<%= link_to(image_tag(img.file.url(:medium)), gallery_image_path(img), :class => "thumbnail") %>
			</li>
			<% end %>
		</ul>
	</div>
	<div class="span6">
		<h2>Comments</h2>
		<div class="well">
			<%= render "comments/comments" %>
			<h6 class="hb">Write your own comment</h6>
			<%= render "comments/form" %>
		</div>
	</div>
</div>