config/routes.rb
Mozapolis::Application.routes.draw do

  root :to => "static#home"

  match 'admin' => "secret#home"
  match 'register' => "static#register"
  resources :pages

  devise_for :fans, :controllers => { :registrations => :fan_registrations }
  resources :fans, :only => [:show, :index]
  resources :fans do 
    resources :comments
  end

  as :fan do
    get    'fan/signin'  => 'devise/sessions#new',     :as => :new_fan_session
    post   'fan/signin'  => 'devise/sessions#create',  :as => :fan_session
    delete 'fan/signout' => 'devise/sessions#destroy', :as => :destroy_fan_session
  end

  devise_for :artists, :controllers => { :registrations => :artist_registrations }
  resources :artists, :only => [:show, :index]
  resources :artists do 
    resources :comments
  end
  as :artist do
    get    'artist/signin'  => 'devise/sessions#new',     :as => :new_artist_session
    post   'artist/signin'  => 'devise/sessions#create',  :as => :artist_session
    delete 'artist/signout' => 'devise/sessions#destroy', :as => :destroy_artist_session
  end

  devise_for :users

  
  resources :notifications
  resources :playlists do
    collection { post :sort }
    resources :ptracks do 
      collection { post :addsong }
    end
  end
  resources :genres
  resources :pictures, :only => [:index, :create, :destroy]
  resources :videos do
    collection { post :sort }
    resources :comments
  end

  resources :events do
    collection { post :sort }
    resources :comments
  end
  resources :articles do
    collection { post :sort }
    resources :comments
  end

  resources :galleries do
    collection { post :sort }
    resources :comments
    resources :images
  end
  resources :images do 
    collection { post :sort }
    resources :comments
  end
  resources :albums do
    collection { post :sort }
    collection { post :upvote }
    collection { post :downvote }
    collection { post :unvote }
    resources :comments
    resources :songs
  end

  
  resources :songs do
    resources :comments
    collection { post :sort }
    collection { post :upvote }
    collection { post :downvote }
    collection { post :unvote }
  end

  namespace :admin do
    resources :articles
    resources :events
    resources :galleries
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  # Relationships
  # -------------
  belongs_to :artist
  has_many :comments, as: :commentable
  
  # Friendly URLS
  # -----
  extend FriendlyId
  friendly_id :title, use: :slugged

  # MASS ASSIGNMENT
  # ---------------
  attr_accessible :about, :end, :start, :ticket_cost, :title, :photo
  
  # Validations
  # -----------
  validates :title,
          presence: true,
          length: {
            minimum: 2, maximum: 40,
            :message => "is too short"
          }  

  validates :start, presence: true
  validates :end, presence: true

  validates :about,
            presence: true,
            length: {
              minimum: 2, maximum: 250,
              :message => "you have exceded 250 letters"
            }
  has_attached_file :photo, 
                      :styles => {
                        :small => "150x150#", 
                        :full_small => "150x150>", 
                        :medium => "400x400#", 
                        :full_medium => "400x400>", 
                        :large => "900x900#", 
                        :full_large => "900x900>",
                        :avatar => "60x60#"
                      },
                    :url => "/system/articles/photos/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/system/articles/photos/:id/:style/:basename.:extension"
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
	def index
		@events = Event.all

		respond_to do |format|
		  format.html # index.html.erb
		  format.json { render json: @events }
		end
	end

	def new
		@artist = current_artist
		@event = @artist.events.build

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @event }
		end
	end

	def create
	  @artist = current_artist
	  @event = @artist.events.build(params[:event])
	  if @event.save
      	flash[:notice] = "<i class='icon-plus'></i> You have created a event succesfully. Wasn't that easy?".html_safe
	    redirect_to admin_events_url
	  else
	    render :action => 'new'
	  end
	end

	def edit
	  @event = Event.find(params[:id])
	end

	def update
	  @event = Event.find(params[:id])

	  respond_to do |format|
	    if @event.update_attributes(params[:event])
          format.html { redirect_to @event, notice: '<i class="icon-edit"></i> Event was successfully updated.'.html_safe }
	      format.json { head :no_content }
	    else
	      format.html { render action: "edit" }
	      format.json { render json: @event.errors, status: :unprocessable_entity }
	    end
	  end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy

		respond_to do |format|
			format.html { redirect_to admin_events_url }
			format.json { head :no_content }
		end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def sort
    params[:event].each_with_index do |id, index|
      Event.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end
  def index
    @events = Event.where(:artist_id => current_artist).order(:position)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def show
    @event = Event.find(params[:id])
    @artist = @event.artist

    # Comments
    @commentable = @event
    @comments = @commentable.comments
    @comment = Comment.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  def new
    @artist = current_artist
    @event = @artist.events.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  def create
    @artist = current_artist
    @event = @artist.events.build(params[:event])
    if @event.save
      flash[:notice] = "You have created a event succesfully. Wasn't that easy?"
      redirect_to events_url
    else
      render :action => 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= simple_form_for [:admin,@event], :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :title %>
  <%= f.input :about, :input_html => { :class => "span4", :rows => 5 } %>
  <hr>
  <%= f.input :start, :input_html => { :class => "span1" } %>
  <%= f.input :end, :input_html => { :class => "span1" } %>
  <hr>
  <%= f.input :photo %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                albums_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<%= provide(:title, 'Editing Event: '+ @event.title) %>
<div class="row">

	<div class="span6 offset3">

	    <ul class="breadcrumb">
			  <li>
			    <%= link_to_icon "lock", "Top Secret", admin_path %> <span class="divider">/</span>
			  </li>
			  <li>
			    <%= link_to_icon "flag", "Manage Events", admin_events_path %> <span class="divider">/</span>
			  </li>
			  <li class="active"><i class="icon-edit"></i> Editing Event: <strong><%= link_to @event.title %></strong></li>
	    </ul>

		<div class="well">
			<%= render :partial => 'form' %>
		</div>

	</div>

	<div class="span3">
		<h6>Current Image</h6>
		<% if @event.photo.file? %>
			<p><%= image_tag @event.photo.url(:medium) %></p>
		<% else %>
			<p>Please upload an event image.</p>
		<% end %>
	</div>
</div>

app/views/admin/events/index.html.erb
<%= provide(:title, 'Manage Events') %>
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <li class="active"><i class="icon-lock"></i> Top Secret</li>
    </ul> 
  </div>
</div>

<div class="row">
	<div class="span3">
		<div class="well">
			<h4><i class="icon-wrench"></i> Events Admin</h4>
			<hr>
			<p>You can edit, view, or delete any event.</p>
		</div>
	</div>
	<div class="span9">
		<div class="pull-right">
			<%= link_to "<i class='icon-plus'></i> New Event".html_safe, new_admin_event_path, :class => "btn btn-success" %>
		</div>
		<h2>All Events</h2>
		<table class="table table-striped table-bordered">
		  <thead>
		    <tr>
		      <th width="30%">Title</th>
		      <th width="20%">Start</th>
		      <th width="20%">End</th>
		      <th width="30%">Options</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% @events.each do |e| %>
		    <tr>
		      <td><%= link_to e.title, e %></td>
		      <td><%= e.start.strftime('%b %d, %Y at %H:%M') %></td>
		      <td><%= e.end.strftime('%b %d, %Y at %H:%M') %></td>
		      <td>
		      	<%= link_to "Edit", edit_admin_event_path(e), :class => "btn btn-mini" %> 
		      	<%= link_to "Delete", event_path(e), :class => "btn btn-danger btn-mini", :confirm => "Are you sure you want to delete this event?", :method => :delete %> 
		      </td>
		    </tr>
		    <% end %>

		  </tbody>
		</table>
		<% if @events.empty? %>
			<div class="alert alert-info">
				<a class="close" data-dismiss="alert" href="#">×</a>
        		There are no events. <%= link_to "<i class='icon-plus'></i> Click here to create one.".html_safe, new_admin_event_path %>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/events/new.html.erb
<%= provide(:title, 'New Event') %>
<div class="row">

	<div class="span6 offset3">

		<ul class="breadcrumb">
			<li>
			  	<%= link_to_icon "lock", "Top Secret", admin_path %> <span class="divider">/</span>
			</li>
			<li>
			  	<%= link_to_icon "flag", "Manage Events", admin_events_path %> <span class="divider">/</span>
			</li>
		  	<li class="active"><i class="icon-plus"></i> New Event</li>
		</ul>	

		<div class="well">
			<%= render :partial => 'form' %>
		</div>

	</div>


</div>