config/routes.rb
Mozapolis::Application.routes.draw do

  root :to => "static#home"

  match 'admin' => "secret#home"
  match 'register' => "static#register"
  resources :pages

  devise_for :fans, :controllers => { :registrations => :fan_registrations }
  resources :fans, :only => [:show, :index]
  resources :fans do 
    resources :comments
  end

  as :fan do
    get    'fan/signin'  => 'devise/sessions#new',     :as => :new_fan_session
    post   'fan/signin'  => 'devise/sessions#create',  :as => :fan_session
    delete 'fan/signout' => 'devise/sessions#destroy', :as => :destroy_fan_session
  end

  devise_for :artists, :controllers => { :registrations => :artist_registrations }
  resources :artists, :only => [:show, :index]
  resources :artists do 
    resources :comments
  end
  as :artist do
    get    'artist/signin'  => 'devise/sessions#new',     :as => :new_artist_session
    post   'artist/signin'  => 'devise/sessions#create',  :as => :artist_session
    delete 'artist/signout' => 'devise/sessions#destroy', :as => :destroy_artist_session
  end

  devise_for :users

  
  resources :notifications
  resources :playlists do
    collection { post :sort }
    resources :ptracks do 
      collection { post :addsong }
    end
  end
  resources :genres
  resources :pictures, :only => [:index, :create, :destroy]
  resources :videos do
    collection { post :sort }
    resources :comments
  end

  resources :events do
    collection { post :sort }
    resources :comments
  end
  resources :articles do
    collection { post :sort }
    resources :comments
  end

  resources :galleries do
    collection { post :sort }
    resources :comments
    resources :images
  end
  resources :images do 
    collection { post :sort }
    resources :comments
  end
  resources :albums do
    collection { post :sort }
    collection { post :upvote }
    collection { post :downvote }
    collection { post :unvote }
    resources :comments
    resources :songs
  end

  
  resources :songs do
    resources :comments
    collection { post :sort }
    collection { post :upvote }
    collection { post :downvote }
    collection { post :unvote }
  end

  namespace :admin do
    resources :articles
    resources :events
    resources :galleries
  end

end

app/views/shared/_message.html.erb
<% flash.each do |name, msg| %>
    <div id="top-alert" class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
<% end %>

app/views/shared/_navbar_search.html.erb
<form class="navbar-search pull-left">
  <input type="text" class="search-query" placeholder="Search">
</form>

app/views/shared/_player.html.erb
    <!---->
    <div id="moz_player"></div>

    <div id="moz_player_container">

        <div id="profile-player" class="btn-group">
          <button class="btn btn-large btn-danger disabled">
            <i class="icon-headphones"></i>
          </button>
          <a href="#" class="jp-play btn btn-large btn-warning" rel="tooltip" title="Play selected track.">
            <i class="icon-play"></i> 
          </a>
          <a href="#" class="jp-pause btn btn-large btn-warning" rel="tooltip" title="Pause selected track.">
            <i class="icon-pause"></i> 
          </a>
          <a href="#" class="jp-stop btn btn-large btn-warning"  rel="tooltip" title="Stop selected track.">
            <i class="icon-stop"></i> 
          </a>
          <a href="#" class="jp-mute btn btn-large btn-info"  rel="tooltip" title="Mute.">
            <i class="icon-volume-off"></i> 
          </a>
          <a href="#" class="jp-unmute btn btn-large disabled btn-inverse" rel="tooltip" title="Unmute.">
            <i class="icon-volume-down"></i> 
          </a>
          <a href="#" class="jp-volume-max btn btn-large btn-info" rel="tooltip" title="Max out volume.">
            <i class="icon-volume-up"></i> 
          </a>
          <button class="btn btn-large disabled">
             <span class="play-state"></span> 
             <strong><span class="track-name"></span></strong> -
             <span class="jp-current-time"></span>:<span class="jp-duration"></span>
          </button>
        </div>

        <table class="table table-bordered">
            <thead>
              <tr>
                <th width="50%">Song Title</th>
                <th width="20%">Vote</th>
                <th width="10%">Plays</th>
                <th width="20%">Comments</th>
              </tr>
            </thead>
            <tbody>
              <% @songs.each do |song| %>
                <tr>
                    <td>
                      <%= link_to song.title, song.file.url, :class => "track track-default" %>
                      <% if fan_signed_in? %>
                        <div class="btn-group pull-right">
                          <a class="btn btn-primary btn-mini dropdown-toggle" data-toggle="dropdown" href="#" rel="tooltip" title="Select a playlist to add the song to it.">
                            <i class="icon-plus"></i>
                            <i class="icon-reorder"></i>
                            <span class="caret"></span>
                          </a>
                          <ul class="dropdown-menu">
                            <% current_fan.playlists.each do |playlist| %>
                              <%= content_tag :li, link_to(playlist.name, addsong_playlist_ptracks_url("song_id" => song.id, "playlist_id" => playlist.id), :method => :post) %>
                            <% end %>
                          </ul>
                        </div>
                      <% end %>
                    </td>
                    <td>
                      <div class="btn-group">
                      <% if artist_signed_in? %>
                        <% if current_artist.voted_on?(song) %>
                          <%= link_to "#{song.votes_for} <i class='icon-thumbs-up'></i>".html_safe, upvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn disabled btn-mini btn-success" %>
                          <%= link_to "#{song.votes_against} <i class='icon-thumbs-down'></i>".html_safe, downvote_songs_url("song_id" => song.id), :method => :post, :class => " vote disabled btn btn-mini btn-danger" %>
                          <%= link_to "<i class='icon-remove'></i>".html_safe, unvote_songs_url("song_id" => song.id), :method => :post, :class => "btn btn-mini btn-inverse" %>
                        <% else %>
                          <%= link_to "#{song.votes_for} <i class='icon-thumbs-up'></i>".html_safe, upvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn btn-mini btn-success" %>
                          <%= link_to "#{song.votes_against} <i class='icon-thumbs-down'></i>".html_safe, downvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn btn-mini btn-danger" %>
                        <% end %>
                      <% elsif fan_signed_in? %>
                        <% if current_fan.voted_on?(song) %>
                          <%= link_to "#{song.votes_for} <i class='icon-thumbs-up'></i>".html_safe, upvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn disabled btn-mini btn-success" %>
                          <%= link_to "#{song.votes_against} <i class='icon-thumbs-down'></i>".html_safe, downvote_songs_url("song_id" => song.id), :method => :post, :class => " vote disabled btn btn-mini btn-danger" %>
                          <%= link_to "<i class='icon-remove'></i>".html_safe, unvote_songs_url("song_id" => song.id), :method => :post, :class => "btn btn-mini btn-inverse" %>
                        <% else %>
                          <%= link_to "#{song.votes_for} <i class='icon-thumbs-up'></i>".html_safe, upvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn btn-mini btn-success" %>
                          <%= link_to "#{song.votes_against} <i class='icon-thumbs-down'></i>".html_safe, downvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn btn-mini btn-danger" %>
                        <% end %>
                      <% end %>
                      </div>
                    </td>
                    <td>2,325</td>
                    <td><%= link_to "<i class='icon-comments'></i> Comments (#{song.comments.count})".html_safe, "#song_#{song.id}", :class => "btn btn-mini", :data => { :toggle => :modal} %></td>
                </tr>
                <% end %>

            </tbody>
        </table>

    </div>

    <!---->
    <% @songs.each do |song| %>
<div class="modal hide fade" id="song_<%= song.id %>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3><%= song.title %> Comments</h3>
  </div>
  <div class="modal-body">
    <% song.comments.each do |comment| %>
      <blockquote>
        <p><%= comment.content %></p>
        <small>
          <% if comment.poster_type == "artist" %>
            <%= link_to comment.artist.artist_name, "#" %> 
          <% else %>
            <%= link_to comment.fan.email, "#" %> 
          <% end %>
              
          on <%= comment.created_at.strftime('%b %d, %Y at %H:%M') %>
        </small>
      </blockquote>
    <% end %>
    <% if song.comments.empty? %>
      <div class="alert alert-warning">There are no comments. Be the first! <a class="close" data-dismiss="alert" href="#">×</a></div>
    <% end %>

  </div>
  <div class="modal-footer">
    <h6>Leave  your own comment</h6>
    <%= simple_form_for [song, Comment.new] do |f| %>
        <%= f.error_notification %>
        <%= f.input :content, :label => false, :as => :text, :input_html => {:class => "span5", :rows => 2}  %>
      <%= f.submit "Submit Comment", :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>
<% end %>

app/views/shared/_playlist.html.erb
    <!---->
    <div id="moz_player"></div>

    <div id="moz_player_container">

        <div id="profile-player" class="btn-group">
          <button class="btn btn-large btn-danger disabled">
            <i class="icon-headphones"></i>
          </button>
          <a href="#" class="jp-play btn btn-large btn-warning" rel="tooltip" title="Play selected track.">
            <i class="icon-play"></i> 
          </a>
          <a href="#" class="jp-pause btn btn-large btn-warning" rel="tooltip" title="Pause selected track.">
            <i class="icon-pause"></i> 
          </a>
          <a href="#" class="jp-stop btn btn-large btn-warning"  rel="tooltip" title="Stop selected track.">
            <i class="icon-stop"></i> 
          </a>
          <a href="#" class="jp-mute btn btn-large btn-info"  rel="tooltip" title="Mute.">
            <i class="icon-volume-off"></i> 
          </a>
          <a href="#" class="jp-unmute btn btn-large disabled btn-inverse" rel="tooltip" title="Unmute.">
            <i class="icon-volume-down"></i> 
          </a>
          <a href="#" class="jp-volume-max btn btn-large btn-info" rel="tooltip" title="Max out volume.">
            <i class="icon-volume-up"></i> 
          </a>
          <button class="btn btn-large disabled">
             <span class="play-state"></span> 
             <strong><span class="track-name"></span></strong> -
             <span class="jp-current-time"></span>:<span class="jp-duration"></span>
          </button>
        </div>

        <table class="table table-bordered">
            <thead>
              <tr>
                <th width="50%">Song Title</th>
                <th width="20%">Vote</th>
                <th width="10%">Plays</th>
                <th width="20%">Comments</th>
              </tr>
            </thead>
            <tbody>
              <% @ptracks.each do |ptrack| song = Song.find(ptrack.song_id) %>
                <tr>
                    <td>
                      <%= link_to song.title, song.file.url, :class => "track track-default" %>

                    </td>
                    <td>
                      <% if artist_signed_in? %>
                        <% if current_artist.voted_on?(song) %>
                          <%= link_to "#{song.votes_for} <i class='icon-thumbs-up'></i>".html_safe, upvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn disabled btn-mini btn-success" %>
                          <%= link_to "#{song.votes_against} <i class='icon-thumbs-down'></i>".html_safe, downvote_songs_url("song_id" => song.id), :method => :post, :class => " vote disabled btn btn-mini btn-danger" %>
                          <%= link_to "<i class='icon-remove'></i>".html_safe, unvote_songs_url("song_id" => song.id), :method => :post, :class => "btn btn-mini btn-inverse" %>
                        <% else %>
                          <%= link_to "#{song.votes_for} <i class='icon-thumbs-up'></i>".html_safe, upvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn btn-mini btn-success" %>
                          <%= link_to "#{song.votes_against} <i class='icon-thumbs-down'></i>".html_safe, downvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn btn-mini btn-danger" %>
                        <% end %>
                      <% elsif %>
                        <% if current_fan.voted_on?(song) %>
                          <%= link_to "#{song.votes_for} <i class='icon-thumbs-up'></i>".html_safe, upvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn disabled btn-mini btn-success" %>
                          <%= link_to "#{song.votes_against} <i class='icon-thumbs-down'></i>".html_safe, downvote_songs_url("song_id" => song.id), :method => :post, :class => " vote disabled btn btn-mini btn-danger" %>
                          <%= link_to "<i class='icon-remove'></i>".html_safe, unvote_songs_url("song_id" => song.id), :method => :post, :class => "btn btn-mini btn-inverse" %>
                        <% else %>
                          <%= link_to "#{song.votes_for} <i class='icon-thumbs-up'></i>".html_safe, upvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn btn-mini btn-success" %>
                          <%= link_to "#{song.votes_against} <i class='icon-thumbs-down'></i>".html_safe, downvote_songs_url("song_id" => song.id), :method => :post, :class => " vote btn btn-mini btn-danger" %>
                        <% end %>
                      <% end %>
                    </td>
                    <td>2,325</td>
                    <td><%= link_to "<i class='icon-comments'></i> Add Comment (#{song.comments.count})".html_safe, "#song_#{song.id}", :data => { :toggle => :modal} %></td>
                </tr>
                <% end %>

            </tbody>
        </table>

    </div>

    <!---->
    <% @ptracks.each do |ptrack| song = Song.find(ptrack.song_id) %>
      <div class="modal hide fade" id="song_<%= song.id %>">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">×</button>
          <h3><%= song.title %> Comments</h3>
        </div>
        <div class="modal-body">
          <% song.comments.each do |comment| %>
            <blockquote>
              <p><%= comment.content %></p>
              <small>
                <% if comment.poster_type == "artist" %>
                  <%= link_to comment.artist.artist_name, "#" %> 
                <% else %>
                  <%= link_to comment.fan.email, "#" %> 
                <% end %>
                    
                on <%= comment.created_at.strftime('%b %d, %Y at %H:%M') %>
              </small>
            </blockquote>
          <% end %>
          <% if song.comments.empty? %>
            <div class="alert alert-warning">There are no comments. Be the first! <a class="close" data-dismiss="alert" href="#">×</a></div>
          <% end %>

        </div>
        <div class="modal-footer">
          <h6>Leave  your own comment</h6>
          <%= simple_form_for [song, Comment.new] do |f| %>
              <%= f.error_notification %>
              <%= f.input :content, :label => false, :as => :text, :input_html => {:class => "span5", :rows => 2}  %>
            <%= f.submit "Submit Comment", :class => "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    <% end %>

app/views/shared/_search.html.erb
<%= form_tag users_path, method: :get, :class => "form-inline", :id => "home-search" do %>
    <div class="control-group well" style="padding:5px;">
      <div class="input-prepend input-append">
        <a class="btn disabled"><i class="icon-search"></i></a><%= text_field_tag :query, params[:query], :id => "typeahead", :class => "span7", :placeholder => "Enter artist name here...", :autocomplete => "off" %><%= submit_tag "Search", name: nil, :class => "btn btn-success" %>
      </div>
      <div class="btn-group pull-right">
        <%= link_to "I need help!", "#", :class => "btn" %>
      </div>
    </div>
<% end %>